# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WuKongNote' do
	
  # Pods for ShareworldPlatform
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'ART'
  ]

  pod 'CodePush', :path =>  '../node_modules/react-native-code-push'

  pod 'react-native-splash-screen', :path =>  '../node_modules/react-native-splash-screen'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'




  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'


 pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  

end
